# No actual modification
# just adding comment
# custom comment 017

AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline for the Sample Lambda Function
Parameters:
  ProjectName:
    Description: Name of the Project
    Type: String
    Default: sample-lambda
  ArtifactBucket:
    Description: S3 Bucket, which will hold the artifacts
    Type: String
  TargetBucket:
    Description: Destination S3 Bucket
    Type: String
  DeveloperAccount:
    Description: AWS AccountNumber where the pipeline reside
    Type: Number
  CMKARN:
    Description: ARN of the KMS CMK creates in Tools account
    Type: String
  Test3:
Resources:
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TargetBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${TargetBucket}
              - !Sub arn:aws:s3:::${TargetBucket}/*
            Principal:
              AWS:
                - !GetAtt [DeployProjectRole,Arn]

  DeployProjectRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-CodeDeployRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                - !Ref DeveloperAccount
            Action:
              - sts:AssumeRole
      Path: /

  DeployProjectPolicy:
    Type: AWS::IAM::Policy
    DependsOn: S3BucketPolicy
    Properties:
      PolicyName: !Sub ${ProjectName}-CodeDeployPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:PutObject
            Resource:
             - arn:aws:s3:::*""
          -
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetBucketPolicy
              - s3:GetObject
              - s3:ListBucket
            Resource:
             - !Join ['',['arn:aws:s3:::',!Ref ArtifactBucket, '/*']]
             - !Join ['',['arn:aws:s3:::',!Ref ArtifactBucket]]
             - !Join ['',['arn:aws:s3:::',!Ref TargetBucket, '/*']]
             - !Join ['',['arn:aws:s3:::',!Ref TargetBucket]]
          -
            Effect: Allow
            Action:
              - kms:*
            Resource: !Ref CMKARN
      Roles:
        -
          !Ref DeployProjectRole

  CFInvalidateRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-CFInvalidateRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                - !Ref DeveloperAccount
            Action:
              - sts:AssumeRole
      Path: /

  CFInvalidatePolicy:
    Type: AWS::IAM::Policy
    DependsOn: S3BucketPolicy
    Properties:
      PolicyName: !Sub ${ProjectName}-CFInvalidatePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - "cloudfront:CreateInvalidation"
            Resource:
             - "*"
      Roles:
        -
          !Ref CFInvalidateRole
