# No actual modification
# just adding comment
# custom comment 017

AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline for the Sample Lambda Function
Parameters:
  ProjectName:
    Description: Name of the Project
    Type: String
    Default: sample-lambda
  ArtifactBucket:
    Description: S3 Bucket, which will hold the artifacts
    Type: String
  TargetBucket:
    Description: Destination S3 Bucket
    Type: String
  DeveloperAccount:
    Description: AWS AccountNumber where the pipeline reside
    Type: Number
  CMKARN:
    Description: ARN of the KMS CMK creates in Tools account
    Type: String
